# Generated by Django 4.1.1 on 2022-10-06 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'ordering': ('date_in',), 'verbose_name_plural': 'User messages'},
        ),
        migrations.AddField(
            model_name='usermessage',
            name='date_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
