# Generated by Django 4.1.1 on 2022-10-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_message', '0002_alter_usermessage_options_usermessage_date_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
