# Generated by Django 4.1.1 on 2022-09-28 10:52

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=apps.models.Gallery.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('position',), 'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterModelOptions(
            name='dishescategory',
            options={'ordering': ('position',), 'verbose_name_plural': 'Dishes Categories'},
        ),
    ]
