# Generated by Django 4.1.1 on 2022-09-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_gallery_alter_about_options_alter_dish_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookTable',
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Galleries'},
        ),
    ]
