# Generated by Django 4.1.1 on 2022-09-28 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Wrong phone number', regex='^(\\d{10})$')])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('people_numb', models.SmallIntegerField()),
                ('message', models.TextField(max_length=300)),
                ('is_processed', models.BooleanField(default=False)),
                ('date_in', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_in',),
            },
        ),
    ]
