# Generated by Django 4.1.1 on 2022-10-01 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booktable',
            options={'ordering': ('date',)},
        ),
        migrations.RemoveField(
            model_name='booktable',
            name='date_in',
        ),
    ]
