# Generated by Django 4.1.1 on 2022-10-05 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_booktable_date_alter_booktable_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Wrong phone number', regex='^(\\d{3}-\\d{3}-\\d{4})$')]),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='time',
            field=models.TimeField(),
        ),
    ]
