# Generated by Django 4.1.1 on 2022-10-05 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_booktable_date_alter_booktable_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booktable',
            options={'ordering': ('date_in',)},
        ),
        migrations.AddField(
            model_name='booktable',
            name='date_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
